// Generated by beansc bindgen for arm64-apple-darwin.

package sys

pub extern "C" opaque struct Fts5Context

pub extern "C" struct Fts5PhraseIter {
    a: RawPtr<u8>
    b: RawPtr<u8>
}

pub extern "C" opaque struct Fts5Tokenizer

pub extern "C" opaque struct Sqlite3

pub extern "C" opaque struct Sqlite3ApiRoutines

pub extern "C" opaque struct Sqlite3Backup

pub extern "C" opaque struct Sqlite3Blob

pub extern "C" opaque struct Sqlite3Context

pub extern "C" struct Sqlite3File {
    pmethods: RawPtr<Sqlite3IoMethods>
}

pub extern "C" struct Sqlite3IndexConstraint {
    icolumn: i32
    op: u8
    usable: u8
    itermoffset: i32
}

pub extern "C" struct Sqlite3IndexConstraintUsage {
    argvindex: i32
    omit: u8
}

pub extern "C" struct Sqlite3IndexInfo {
    nconstraint: i32
    aconstraint: RawPtr<Sqlite3IndexConstraint>
    norderby: i32
    aorderby: RawPtr<Sqlite3IndexOrderby>
    aconstraintusage: RawPtr<Sqlite3IndexConstraintUsage>
    idxnum: i32
    idxstr: RawPtr<i8>
    needtofreeidxstr: i32
    orderbyconsumed: i32
    estimatedcost: f64
    estimatedrows: i64
    idxflags: i32
    colused: u64
}

pub extern "C" struct Sqlite3IndexOrderby {
    icolumn: i32
    desc: u8
}

pub extern "C" struct Sqlite3IoMethods {
    iversion: i32
    xclose: CFunctionPtr<fn(RawPtr<Sqlite3File>) -> i32>
    xread: CFunctionPtr<fn(RawPtr<Sqlite3File>, RawPtr<u8>, i32, i64) -> i32>
    xwrite: CFunctionPtr<fn(RawPtr<Sqlite3File>, RawPtr<u8>, i32, i64) -> i32>
    xtruncate: CFunctionPtr<fn(RawPtr<Sqlite3File>, i64) -> i32>
    xsync: CFunctionPtr<fn(RawPtr<Sqlite3File>, i32) -> i32>
    xfilesize: CFunctionPtr<fn(RawPtr<Sqlite3File>, RawPtr<i64>) -> i32>
    xlock: CFunctionPtr<fn(RawPtr<Sqlite3File>, i32) -> i32>
    xunlock: CFunctionPtr<fn(RawPtr<Sqlite3File>, i32) -> i32>
    xcheckreservedlock: CFunctionPtr<fn(RawPtr<Sqlite3File>, RawPtr<i32>) -> i32>
    xfilecontrol: CFunctionPtr<fn(RawPtr<Sqlite3File>, i32, RawPtr<u8>) -> i32>
    xsectorsize: CFunctionPtr<fn(RawPtr<Sqlite3File>) -> i32>
    xdevicecharacteristics: CFunctionPtr<fn(RawPtr<Sqlite3File>) -> i32>
    xshmmap: CFunctionPtr<fn(RawPtr<Sqlite3File>, i32, i32, i32, RawPtr<RawPtr<u8> >) -> i32>
    xshmlock: CFunctionPtr<fn(RawPtr<Sqlite3File>, i32, i32, i32) -> i32>
    xshmbarrier: CFunctionPtr<fn(RawPtr<Sqlite3File>)>
    xshmunmap: CFunctionPtr<fn(RawPtr<Sqlite3File>, i32) -> i32>
    xfetch: CFunctionPtr<fn(RawPtr<Sqlite3File>, i64, i32, RawPtr<RawPtr<u8> >) -> i32>
    xunfetch: CFunctionPtr<fn(RawPtr<Sqlite3File>, i64, RawPtr<u8>) -> i32>
}

pub extern "C" struct Sqlite3MemMethods {
    xmalloc: CFunctionPtr<fn(i32) -> RawPtr<u8> >
    xfree: CFunctionPtr<fn(RawPtr<u8>)>
    xrealloc: CFunctionPtr<fn(RawPtr<u8>, i32) -> RawPtr<u8> >
    xsize: CFunctionPtr<fn(RawPtr<u8>) -> i32>
    xroundup: CFunctionPtr<fn(i32) -> i32>
    xinit: CFunctionPtr<fn(RawPtr<u8>) -> i32>
    xshutdown: CFunctionPtr<fn(RawPtr<u8>)>
    pappdata: RawPtr<u8>
}

pub extern "C" struct Sqlite3Module {
    iversion: i32
    xcreate: CFunctionPtr<fn(RawPtr<Sqlite3>, RawPtr<u8>, i32, RawPtr<RawPtr<i8> >, RawPtr<RawPtr<Sqlite3Vtab> >, RawPtr<RawPtr<i8> >) -> i32>
    xconnect: CFunctionPtr<fn(RawPtr<Sqlite3>, RawPtr<u8>, i32, RawPtr<RawPtr<i8> >, RawPtr<RawPtr<Sqlite3Vtab> >, RawPtr<RawPtr<i8> >) -> i32>
    xbestindex: CFunctionPtr<fn(RawPtr<Sqlite3Vtab>, RawPtr<Sqlite3IndexInfo>) -> i32>
    xdisconnect: CFunctionPtr<fn(RawPtr<Sqlite3Vtab>) -> i32>
    xdestroy: CFunctionPtr<fn(RawPtr<Sqlite3Vtab>) -> i32>
    xopen: CFunctionPtr<fn(RawPtr<Sqlite3Vtab>, RawPtr<RawPtr<Sqlite3VtabCursor> >) -> i32>
    xclose: CFunctionPtr<fn(RawPtr<Sqlite3VtabCursor>) -> i32>
    xfilter: CFunctionPtr<fn(RawPtr<Sqlite3VtabCursor>, i32, RawPtr<i8>, i32, RawPtr<RawPtr<Sqlite3Value> >) -> i32>
    xnext: CFunctionPtr<fn(RawPtr<Sqlite3VtabCursor>) -> i32>
    xeof: CFunctionPtr<fn(RawPtr<Sqlite3VtabCursor>) -> i32>
    xcolumn: CFunctionPtr<fn(RawPtr<Sqlite3VtabCursor>, RawPtr<Sqlite3Context>, i32) -> i32>
    xrowid: CFunctionPtr<fn(RawPtr<Sqlite3VtabCursor>, RawPtr<i64>) -> i32>
    xupdate: CFunctionPtr<fn(RawPtr<Sqlite3Vtab>, i32, RawPtr<RawPtr<Sqlite3Value> >, RawPtr<i64>) -> i32>
    xbegin: CFunctionPtr<fn(RawPtr<Sqlite3Vtab>) -> i32>
    xsync: CFunctionPtr<fn(RawPtr<Sqlite3Vtab>) -> i32>
    xcommit: CFunctionPtr<fn(RawPtr<Sqlite3Vtab>) -> i32>
    xrollback: CFunctionPtr<fn(RawPtr<Sqlite3Vtab>) -> i32>
    xfindfunction: CFunctionPtr<fn(RawPtr<Sqlite3Vtab>, i32, RawPtr<i8>, RawPtr<CFunctionPtr<fn(RawPtr<Sqlite3Context>, i32, RawPtr<RawPtr<Sqlite3Value> >)> >, RawPtr<RawPtr<u8> >) -> i32>
    xrename: CFunctionPtr<fn(RawPtr<Sqlite3Vtab>, RawPtr<i8>) -> i32>
    xsavepoint: CFunctionPtr<fn(RawPtr<Sqlite3Vtab>, i32) -> i32>
    xrelease: CFunctionPtr<fn(RawPtr<Sqlite3Vtab>, i32) -> i32>
    xrollbackto: CFunctionPtr<fn(RawPtr<Sqlite3Vtab>, i32) -> i32>
    xshadowname: CFunctionPtr<fn(RawPtr<i8>) -> i32>
    xintegrity: CFunctionPtr<fn(RawPtr<Sqlite3Vtab>, RawPtr<i8>, RawPtr<i8>, i32, RawPtr<RawPtr<i8> >) -> i32>
}

pub extern "C" opaque struct Sqlite3Mutex

pub extern "C" struct Sqlite3MutexMethods {
    xmutexinit: CFunctionPtr<fn() -> i32>
    xmutexend: CFunctionPtr<fn() -> i32>
    xmutexalloc: CFunctionPtr<fn(i32) -> RawPtr<Sqlite3Mutex> >
    xmutexfree: CFunctionPtr<fn(RawPtr<Sqlite3Mutex>)>
    xmutexenter: CFunctionPtr<fn(RawPtr<Sqlite3Mutex>)>
    xmutextry: CFunctionPtr<fn(RawPtr<Sqlite3Mutex>) -> i32>
    xmutexleave: CFunctionPtr<fn(RawPtr<Sqlite3Mutex>)>
    xmutexheld: CFunctionPtr<fn(RawPtr<Sqlite3Mutex>) -> i32>
    xmutexnotheld: CFunctionPtr<fn(RawPtr<Sqlite3Mutex>) -> i32>
}

pub extern "C" opaque struct Sqlite3Pcache

pub extern "C" struct Sqlite3PcacheMethods {
    parg: RawPtr<u8>
    xinit: CFunctionPtr<fn(RawPtr<u8>) -> i32>
    xshutdown: CFunctionPtr<fn(RawPtr<u8>)>
    xcreate: CFunctionPtr<fn(i32, i32) -> RawPtr<Sqlite3Pcache> >
    xcachesize: CFunctionPtr<fn(RawPtr<Sqlite3Pcache>, i32)>
    xpagecount: CFunctionPtr<fn(RawPtr<Sqlite3Pcache>) -> i32>
    xfetch: CFunctionPtr<fn(RawPtr<Sqlite3Pcache>, u32, i32) -> RawPtr<u8> >
    xunpin: CFunctionPtr<fn(RawPtr<Sqlite3Pcache>, RawPtr<u8>, i32)>
    xrekey: CFunctionPtr<fn(RawPtr<Sqlite3Pcache>, RawPtr<u8>, u32, u32)>
    xtruncate: CFunctionPtr<fn(RawPtr<Sqlite3Pcache>, u32)>
    xdestroy: CFunctionPtr<fn(RawPtr<Sqlite3Pcache>)>
}

pub extern "C" struct Sqlite3PcacheMethods2 {
    iversion: i32
    parg: RawPtr<u8>
    xinit: CFunctionPtr<fn(RawPtr<u8>) -> i32>
    xshutdown: CFunctionPtr<fn(RawPtr<u8>)>
    xcreate: CFunctionPtr<fn(i32, i32, i32) -> RawPtr<Sqlite3Pcache> >
    xcachesize: CFunctionPtr<fn(RawPtr<Sqlite3Pcache>, i32)>
    xpagecount: CFunctionPtr<fn(RawPtr<Sqlite3Pcache>) -> i32>
    xfetch: CFunctionPtr<fn(RawPtr<Sqlite3Pcache>, u32, i32) -> RawPtr<Sqlite3PcachePage> >
    xunpin: CFunctionPtr<fn(RawPtr<Sqlite3Pcache>, RawPtr<Sqlite3PcachePage>, i32)>
    xrekey: CFunctionPtr<fn(RawPtr<Sqlite3Pcache>, RawPtr<Sqlite3PcachePage>, u32, u32)>
    xtruncate: CFunctionPtr<fn(RawPtr<Sqlite3Pcache>, u32)>
    xdestroy: CFunctionPtr<fn(RawPtr<Sqlite3Pcache>)>
    xshrink: CFunctionPtr<fn(RawPtr<Sqlite3Pcache>)>
}

pub extern "C" struct Sqlite3PcachePage {
    pbuf: RawPtr<u8>
    pextra: RawPtr<u8>
}

pub extern "C" struct Sqlite3RtreeGeometry {
    pcontext: RawPtr<u8>
    nparam: i32
    aparam: RawPtr<f64>
    puser: RawPtr<u8>
    xdeluser: CFunctionPtr<fn(RawPtr<u8>)>
}

pub extern "C" struct Sqlite3RtreeQueryInfo {
    pcontext: RawPtr<u8>
    nparam: i32
    aparam: RawPtr<f64>
    puser: RawPtr<u8>
    xdeluser: CFunctionPtr<fn(RawPtr<u8>)>
    acoord: RawPtr<f64>
    anqueue: RawPtr<u32>
    ncoord: i32
    ilevel: i32
    mxlevel: i32
    irowid: i64
    rparentscore: f64
    eparentwithin: i32
    ewithin: i32
    rscore: f64
    apsqlparam: RawPtr<RawPtr<Sqlite3Value> >
}

pub extern "C" struct Sqlite3Snapshot {
    hidden: [u8; 48]
}

pub extern "C" opaque struct Sqlite3Stmt

pub extern "C" opaque struct Sqlite3Str

pub extern "C" opaque struct Sqlite3Value

pub extern "C" struct Sqlite3Vfs {
    iversion: i32
    szosfile: i32
    mxpathname: i32
    pnext: RawPtr<Sqlite3Vfs>
    zname: RawPtr<i8>
    pappdata: RawPtr<u8>
    xopen: CFunctionPtr<fn(RawPtr<Sqlite3Vfs>, RawPtr<i8>, RawPtr<Sqlite3File>, i32, RawPtr<i32>) -> i32>
    xdelete: CFunctionPtr<fn(RawPtr<Sqlite3Vfs>, RawPtr<i8>, i32) -> i32>
    xaccess: CFunctionPtr<fn(RawPtr<Sqlite3Vfs>, RawPtr<i8>, i32, RawPtr<i32>) -> i32>
    xfullpathname: CFunctionPtr<fn(RawPtr<Sqlite3Vfs>, RawPtr<i8>, i32, RawPtr<i8>) -> i32>
    xdlopen: CFunctionPtr<fn(RawPtr<Sqlite3Vfs>, RawPtr<i8>) -> RawPtr<u8> >
    xdlerror: CFunctionPtr<fn(RawPtr<Sqlite3Vfs>, i32, RawPtr<i8>)>
    xdlsym: CFunctionPtr<fn(RawPtr<Sqlite3Vfs>, RawPtr<u8>, RawPtr<i8>) -> CFunctionPtr<fn()> >
    xdlclose: CFunctionPtr<fn(RawPtr<Sqlite3Vfs>, RawPtr<u8>)>
    xrandomness: CFunctionPtr<fn(RawPtr<Sqlite3Vfs>, i32, RawPtr<i8>) -> i32>
    xsleep: CFunctionPtr<fn(RawPtr<Sqlite3Vfs>, i32) -> i32>
    xcurrenttime: CFunctionPtr<fn(RawPtr<Sqlite3Vfs>, RawPtr<f64>) -> i32>
    xgetlasterror: CFunctionPtr<fn(RawPtr<Sqlite3Vfs>, i32, RawPtr<i8>) -> i32>
    xcurrenttimeint64: CFunctionPtr<fn(RawPtr<Sqlite3Vfs>, RawPtr<i64>) -> i32>
    xsetsystemcall: CFunctionPtr<fn(RawPtr<Sqlite3Vfs>, RawPtr<i8>, CFunctionPtr<fn()>) -> i32>
    xgetsystemcall: CFunctionPtr<fn(RawPtr<Sqlite3Vfs>, RawPtr<i8>) -> CFunctionPtr<fn()> >
    xnextsystemcall: CFunctionPtr<fn(RawPtr<Sqlite3Vfs>, RawPtr<i8>) -> RawPtr<i8> >
}

pub extern "C" struct Sqlite3Vtab {
    pmodule: RawPtr<Sqlite3Module>
    nref: i32
    zerrmsg: RawPtr<i8>
}

pub extern "C" struct Sqlite3VtabCursor {
    pvtab: RawPtr<Sqlite3Vtab>
}

pub extern "C" fn sqlite3_libversion() -> RawPtr<i8>
pub extern "C" fn sqlite3_sourceid() -> RawPtr<i8>
pub extern "C" fn sqlite3_libversion_number() -> i32
pub extern "C" fn sqlite3_compileoption_used(zoptname: RawPtr<i8>) -> i32
pub extern "C" fn sqlite3_compileoption_get(n: i32) -> RawPtr<i8>
pub extern "C" fn sqlite3_threadsafe() -> i32
pub extern "C" fn sqlite3_close(arg0: RawPtr<Sqlite3>) -> i32
pub extern "C" fn sqlite3_close_v2(arg0: RawPtr<Sqlite3>) -> i32
pub extern "C" fn sqlite3_exec(arg0: RawPtr<Sqlite3>, sql: RawPtr<i8>, callback: fn(RawPtr<u8>, i32, RawPtr<RawPtr<i8> >, RawPtr<RawPtr<i8> >) -> i32, arg3: RawPtr<u8>, errmsg: RawPtr<RawPtr<i8> >) -> i32
pub extern "C" fn sqlite3_initialize() -> i32
pub extern "C" fn sqlite3_shutdown() -> i32
pub extern "C" fn sqlite3_os_init() -> i32
pub extern "C" fn sqlite3_os_end() -> i32
pub extern "C" fn sqlite3_extended_result_codes(arg0: RawPtr<Sqlite3>, onoff: i32) -> i32
pub extern "C" fn sqlite3_last_insert_rowid(arg0: RawPtr<Sqlite3>) -> i64
pub extern "C" fn sqlite3_set_last_insert_rowid(arg0: RawPtr<Sqlite3>, arg1: i64)
pub extern "C" fn sqlite3_changes(arg0: RawPtr<Sqlite3>) -> i32
pub extern "C" fn sqlite3_changes64(arg0: RawPtr<Sqlite3>) -> i64
pub extern "C" fn sqlite3_total_changes(arg0: RawPtr<Sqlite3>) -> i32
pub extern "C" fn sqlite3_total_changes64(arg0: RawPtr<Sqlite3>) -> i64
pub extern "C" fn sqlite3_interrupt(arg0: RawPtr<Sqlite3>)
pub extern "C" fn sqlite3_is_interrupted(arg0: RawPtr<Sqlite3>) -> i32
pub extern "C" fn sqlite3_complete(sql: RawPtr<i8>) -> i32
pub extern "C" fn sqlite3_complete16(sql: RawPtr<u8>) -> i32
pub extern "C" fn sqlite3_busy_handler(arg0: RawPtr<Sqlite3>, arg1: fn(RawPtr<u8>, i32) -> i32, arg2: RawPtr<u8>) -> i32
pub extern "C" fn sqlite3_busy_timeout(arg0: RawPtr<Sqlite3>, ms: i32) -> i32
pub extern "C" fn sqlite3_setlk_timeout(arg0: RawPtr<Sqlite3>, ms: i32, flags: i32) -> i32
pub extern "C" fn sqlite3_get_table(db: RawPtr<Sqlite3>, zsql: RawPtr<i8>, pazresult: RawPtr<RawPtr<RawPtr<i8> > >, pnrow: RawPtr<i32>, pncolumn: RawPtr<i32>, pzerrmsg: RawPtr<RawPtr<i8> >) -> i32
pub extern "C" fn sqlite3_free_table(result: RawPtr<RawPtr<i8> >)
pub extern "C" fn sqlite3_vmprintf(arg0: RawPtr<i8>, arg1: RawPtr<i8>) -> RawPtr<i8>
pub extern "C" fn sqlite3_vsnprintf(arg0: i32, arg1: RawPtr<i8>, arg2: RawPtr<i8>, arg3: RawPtr<i8>) -> RawPtr<i8>
pub extern "C" fn sqlite3_malloc(arg0: i32) -> RawPtr<u8>
pub extern "C" fn sqlite3_malloc64(arg0: u64) -> RawPtr<u8>
pub extern "C" fn sqlite3_realloc(arg0: RawPtr<u8>, arg1: i32) -> RawPtr<u8>
pub extern "C" fn sqlite3_realloc64(arg0: RawPtr<u8>, arg1: u64) -> RawPtr<u8>
pub extern "C" fn sqlite3_free(arg0: RawPtr<u8>)
pub extern "C" fn sqlite3_msize(arg0: RawPtr<u8>) -> u64
pub extern "C" fn sqlite3_memory_used() -> i64
pub extern "C" fn sqlite3_memory_highwater(resetflag: i32) -> i64
pub extern "C" fn sqlite3_randomness(n: i32, p: RawPtr<u8>)
pub extern "C" fn sqlite3_set_authorizer(arg0: RawPtr<Sqlite3>, xauth: fn(RawPtr<u8>, i32, RawPtr<i8>, RawPtr<i8>, RawPtr<i8>, RawPtr<i8>) -> i32, puserdata: RawPtr<u8>) -> i32
pub extern "C" fn sqlite3_trace(arg0: RawPtr<Sqlite3>, xtrace: fn(RawPtr<u8>, RawPtr<i8>), arg2: RawPtr<u8>) -> RawPtr<u8>
pub extern "C" fn sqlite3_profile(arg0: RawPtr<Sqlite3>, xprofile: fn(RawPtr<u8>, RawPtr<i8>, u64), arg2: RawPtr<u8>) -> RawPtr<u8>
pub extern "C" fn sqlite3_trace_v2(arg0: RawPtr<Sqlite3>, umask: u32, xcallback: fn(u32, RawPtr<u8>, RawPtr<u8>, RawPtr<u8>) -> i32, pctx: RawPtr<u8>) -> i32
pub extern "C" fn sqlite3_progress_handler(arg0: RawPtr<Sqlite3>, arg1: i32, arg2: fn(RawPtr<u8>) -> i32, arg3: RawPtr<u8>)
pub extern "C" fn sqlite3_open(filename: RawPtr<i8>, ppdb: RawPtr<RawPtr<Sqlite3> >) -> i32
pub extern "C" fn sqlite3_open16(filename: RawPtr<u8>, ppdb: RawPtr<RawPtr<Sqlite3> >) -> i32
pub extern "C" fn sqlite3_open_v2(filename: RawPtr<i8>, ppdb: RawPtr<RawPtr<Sqlite3> >, flags: i32, zvfs: RawPtr<i8>) -> i32
pub extern "C" fn sqlite3_uri_parameter(z: RawPtr<i8>, zparam: RawPtr<i8>) -> RawPtr<i8>
pub extern "C" fn sqlite3_uri_boolean(z: RawPtr<i8>, zparam: RawPtr<i8>, bdefault: i32) -> i32
pub extern "C" fn sqlite3_uri_int64(arg0: RawPtr<i8>, arg1: RawPtr<i8>, arg2: i64) -> i64
pub extern "C" fn sqlite3_uri_key(z: RawPtr<i8>, n: i32) -> RawPtr<i8>
pub extern "C" fn sqlite3_filename_database(arg0: RawPtr<i8>) -> RawPtr<i8>
pub extern "C" fn sqlite3_filename_journal(arg0: RawPtr<i8>) -> RawPtr<i8>
pub extern "C" fn sqlite3_filename_wal(arg0: RawPtr<i8>) -> RawPtr<i8>
pub extern "C" fn sqlite3_database_file_object(arg0: RawPtr<i8>) -> RawPtr<Sqlite3File>
pub extern "C" fn sqlite3_create_filename(zdatabase: RawPtr<i8>, zjournal: RawPtr<i8>, zwal: RawPtr<i8>, nparam: i32, azparam: RawPtr<RawPtr<i8> >) -> RawPtr<i8>
pub extern "C" fn sqlite3_free_filename(arg0: RawPtr<i8>)
pub extern "C" fn sqlite3_errcode(db: RawPtr<Sqlite3>) -> i32
pub extern "C" fn sqlite3_extended_errcode(db: RawPtr<Sqlite3>) -> i32
pub extern "C" fn sqlite3_errmsg(arg0: RawPtr<Sqlite3>) -> RawPtr<i8>
pub extern "C" fn sqlite3_errmsg16(arg0: RawPtr<Sqlite3>) -> RawPtr<u8>
pub extern "C" fn sqlite3_errstr(arg0: i32) -> RawPtr<i8>
pub extern "C" fn sqlite3_error_offset(db: RawPtr<Sqlite3>) -> i32
pub extern "C" fn sqlite3_set_errmsg(db: RawPtr<Sqlite3>, errcode: i32, zerrmsg: RawPtr<i8>) -> i32
pub extern "C" fn sqlite3_limit(arg0: RawPtr<Sqlite3>, id: i32, newval: i32) -> i32
pub extern "C" fn sqlite3_prepare(db: RawPtr<Sqlite3>, zsql: RawPtr<i8>, nbyte: i32, ppstmt: RawPtr<RawPtr<Sqlite3Stmt> >, pztail: RawPtr<RawPtr<i8> >) -> i32
pub extern "C" fn sqlite3_prepare_v2(db: RawPtr<Sqlite3>, zsql: RawPtr<i8>, nbyte: i32, ppstmt: RawPtr<RawPtr<Sqlite3Stmt> >, pztail: RawPtr<RawPtr<i8> >) -> i32
pub extern "C" fn sqlite3_prepare_v3(db: RawPtr<Sqlite3>, zsql: RawPtr<i8>, nbyte: i32, prepflags: u32, ppstmt: RawPtr<RawPtr<Sqlite3Stmt> >, pztail: RawPtr<RawPtr<i8> >) -> i32
pub extern "C" fn sqlite3_prepare16(db: RawPtr<Sqlite3>, zsql: RawPtr<u8>, nbyte: i32, ppstmt: RawPtr<RawPtr<Sqlite3Stmt> >, pztail: RawPtr<RawPtr<u8> >) -> i32
pub extern "C" fn sqlite3_prepare16_v2(db: RawPtr<Sqlite3>, zsql: RawPtr<u8>, nbyte: i32, ppstmt: RawPtr<RawPtr<Sqlite3Stmt> >, pztail: RawPtr<RawPtr<u8> >) -> i32
pub extern "C" fn sqlite3_prepare16_v3(db: RawPtr<Sqlite3>, zsql: RawPtr<u8>, nbyte: i32, prepflags: u32, ppstmt: RawPtr<RawPtr<Sqlite3Stmt> >, pztail: RawPtr<RawPtr<u8> >) -> i32
pub extern "C" fn sqlite3_sql(pstmt: RawPtr<Sqlite3Stmt>) -> RawPtr<i8>
pub extern "C" fn sqlite3_expanded_sql(pstmt: RawPtr<Sqlite3Stmt>) -> RawPtr<i8>
pub extern "C" fn sqlite3_stmt_readonly(pstmt: RawPtr<Sqlite3Stmt>) -> i32
pub extern "C" fn sqlite3_stmt_isexplain(pstmt: RawPtr<Sqlite3Stmt>) -> i32
pub extern "C" fn sqlite3_stmt_explain(pstmt: RawPtr<Sqlite3Stmt>, emode: i32) -> i32
pub extern "C" fn sqlite3_stmt_busy(arg0: RawPtr<Sqlite3Stmt>) -> i32
pub extern "C" fn sqlite3_bind_blob(arg0: RawPtr<Sqlite3Stmt>, arg1: i32, arg2: RawPtr<u8>, n: i32, arg4: fn(RawPtr<u8>)) -> i32
pub extern "C" fn sqlite3_bind_blob64(arg0: RawPtr<Sqlite3Stmt>, arg1: i32, arg2: RawPtr<u8>, arg3: u64, arg4: fn(RawPtr<u8>)) -> i32
pub extern "C" fn sqlite3_bind_double(arg0: RawPtr<Sqlite3Stmt>, arg1: i32, arg2: f64) -> i32
pub extern "C" fn sqlite3_bind_int(arg0: RawPtr<Sqlite3Stmt>, arg1: i32, arg2: i32) -> i32
pub extern "C" fn sqlite3_bind_int64(arg0: RawPtr<Sqlite3Stmt>, arg1: i32, arg2: i64) -> i32
pub extern "C" fn sqlite3_bind_null(arg0: RawPtr<Sqlite3Stmt>, arg1: i32) -> i32
pub extern "C" fn sqlite3_bind_text(arg0: RawPtr<Sqlite3Stmt>, arg1: i32, arg2: RawPtr<i8>, arg3: i32, arg4: fn(RawPtr<u8>)) -> i32
pub extern "C" fn sqlite3_bind_text16(arg0: RawPtr<Sqlite3Stmt>, arg1: i32, arg2: RawPtr<u8>, arg3: i32, arg4: fn(RawPtr<u8>)) -> i32
pub extern "C" fn sqlite3_bind_text64(arg0: RawPtr<Sqlite3Stmt>, arg1: i32, arg2: RawPtr<i8>, arg3: u64, arg4: fn(RawPtr<u8>), encoding: u8) -> i32
pub extern "C" fn sqlite3_bind_value(arg0: RawPtr<Sqlite3Stmt>, arg1: i32, arg2: RawPtr<Sqlite3Value>) -> i32
pub extern "C" fn sqlite3_bind_pointer(arg0: RawPtr<Sqlite3Stmt>, arg1: i32, arg2: RawPtr<u8>, arg3: RawPtr<i8>, arg4: fn(RawPtr<u8>)) -> i32
pub extern "C" fn sqlite3_bind_zeroblob(arg0: RawPtr<Sqlite3Stmt>, arg1: i32, n: i32) -> i32
pub extern "C" fn sqlite3_bind_zeroblob64(arg0: RawPtr<Sqlite3Stmt>, arg1: i32, arg2: u64) -> i32
pub extern "C" fn sqlite3_bind_parameter_count(arg0: RawPtr<Sqlite3Stmt>) -> i32
pub extern "C" fn sqlite3_bind_parameter_name(arg0: RawPtr<Sqlite3Stmt>, arg1: i32) -> RawPtr<i8>
pub extern "C" fn sqlite3_bind_parameter_index(arg0: RawPtr<Sqlite3Stmt>, zname: RawPtr<i8>) -> i32
pub extern "C" fn sqlite3_clear_bindings(arg0: RawPtr<Sqlite3Stmt>) -> i32
pub extern "C" fn sqlite3_column_count(pstmt: RawPtr<Sqlite3Stmt>) -> i32
pub extern "C" fn sqlite3_column_name(arg0: RawPtr<Sqlite3Stmt>, n: i32) -> RawPtr<i8>
pub extern "C" fn sqlite3_column_name16(arg0: RawPtr<Sqlite3Stmt>, n: i32) -> RawPtr<u8>
pub extern "C" fn sqlite3_column_database_name(arg0: RawPtr<Sqlite3Stmt>, arg1: i32) -> RawPtr<i8>
pub extern "C" fn sqlite3_column_database_name16(arg0: RawPtr<Sqlite3Stmt>, arg1: i32) -> RawPtr<u8>
pub extern "C" fn sqlite3_column_table_name(arg0: RawPtr<Sqlite3Stmt>, arg1: i32) -> RawPtr<i8>
pub extern "C" fn sqlite3_column_table_name16(arg0: RawPtr<Sqlite3Stmt>, arg1: i32) -> RawPtr<u8>
pub extern "C" fn sqlite3_column_origin_name(arg0: RawPtr<Sqlite3Stmt>, arg1: i32) -> RawPtr<i8>
pub extern "C" fn sqlite3_column_origin_name16(arg0: RawPtr<Sqlite3Stmt>, arg1: i32) -> RawPtr<u8>
pub extern "C" fn sqlite3_column_decltype(arg0: RawPtr<Sqlite3Stmt>, arg1: i32) -> RawPtr<i8>
pub extern "C" fn sqlite3_column_decltype16(arg0: RawPtr<Sqlite3Stmt>, arg1: i32) -> RawPtr<u8>
pub extern "C" fn sqlite3_step(arg0: RawPtr<Sqlite3Stmt>) -> i32
pub extern "C" fn sqlite3_data_count(pstmt: RawPtr<Sqlite3Stmt>) -> i32
pub extern "C" fn sqlite3_column_blob(arg0: RawPtr<Sqlite3Stmt>, icol: i32) -> RawPtr<u8>
pub extern "C" fn sqlite3_column_double(arg0: RawPtr<Sqlite3Stmt>, icol: i32) -> f64
pub extern "C" fn sqlite3_column_int(arg0: RawPtr<Sqlite3Stmt>, icol: i32) -> i32
pub extern "C" fn sqlite3_column_int64(arg0: RawPtr<Sqlite3Stmt>, icol: i32) -> i64
pub extern "C" fn sqlite3_column_text(arg0: RawPtr<Sqlite3Stmt>, icol: i32) -> RawPtr<u8>
pub extern "C" fn sqlite3_column_text16(arg0: RawPtr<Sqlite3Stmt>, icol: i32) -> RawPtr<u8>
pub extern "C" fn sqlite3_column_value(arg0: RawPtr<Sqlite3Stmt>, icol: i32) -> RawPtr<Sqlite3Value>
pub extern "C" fn sqlite3_column_bytes(arg0: RawPtr<Sqlite3Stmt>, icol: i32) -> i32
pub extern "C" fn sqlite3_column_bytes16(arg0: RawPtr<Sqlite3Stmt>, icol: i32) -> i32
pub extern "C" fn sqlite3_column_type(arg0: RawPtr<Sqlite3Stmt>, icol: i32) -> i32
pub extern "C" fn sqlite3_finalize(pstmt: RawPtr<Sqlite3Stmt>) -> i32
pub extern "C" fn sqlite3_reset(pstmt: RawPtr<Sqlite3Stmt>) -> i32
pub extern "C" fn sqlite3_create_function(db: RawPtr<Sqlite3>, zfunctionname: RawPtr<i8>, narg: i32, etextrep: i32, papp: RawPtr<u8>, xfunc: fn(RawPtr<Sqlite3Context>, i32, RawPtr<RawPtr<Sqlite3Value> >), xstep: fn(RawPtr<Sqlite3Context>, i32, RawPtr<RawPtr<Sqlite3Value> >), xfinal: fn(RawPtr<Sqlite3Context>)) -> i32
pub extern "C" fn sqlite3_create_function16(db: RawPtr<Sqlite3>, zfunctionname: RawPtr<u8>, narg: i32, etextrep: i32, papp: RawPtr<u8>, xfunc: fn(RawPtr<Sqlite3Context>, i32, RawPtr<RawPtr<Sqlite3Value> >), xstep: fn(RawPtr<Sqlite3Context>, i32, RawPtr<RawPtr<Sqlite3Value> >), xfinal: fn(RawPtr<Sqlite3Context>)) -> i32
pub extern "C" fn sqlite3_create_function_v2(db: RawPtr<Sqlite3>, zfunctionname: RawPtr<i8>, narg: i32, etextrep: i32, papp: RawPtr<u8>, xfunc: fn(RawPtr<Sqlite3Context>, i32, RawPtr<RawPtr<Sqlite3Value> >), xstep: fn(RawPtr<Sqlite3Context>, i32, RawPtr<RawPtr<Sqlite3Value> >), xfinal: fn(RawPtr<Sqlite3Context>), xdestroy: fn(RawPtr<u8>)) -> i32
pub extern "C" fn sqlite3_create_window_function(db: RawPtr<Sqlite3>, zfunctionname: RawPtr<i8>, narg: i32, etextrep: i32, papp: RawPtr<u8>, xstep: fn(RawPtr<Sqlite3Context>, i32, RawPtr<RawPtr<Sqlite3Value> >), xfinal: fn(RawPtr<Sqlite3Context>), xvalue: fn(RawPtr<Sqlite3Context>), xinverse: fn(RawPtr<Sqlite3Context>, i32, RawPtr<RawPtr<Sqlite3Value> >), xdestroy: fn(RawPtr<u8>)) -> i32
pub extern "C" fn sqlite3_aggregate_count(arg0: RawPtr<Sqlite3Context>) -> i32
pub extern "C" fn sqlite3_expired(arg0: RawPtr<Sqlite3Stmt>) -> i32
pub extern "C" fn sqlite3_transfer_bindings(arg0: RawPtr<Sqlite3Stmt>, arg1: RawPtr<Sqlite3Stmt>) -> i32
pub extern "C" fn sqlite3_global_recover() -> i32
pub extern "C" fn sqlite3_thread_cleanup()
pub extern "C" fn sqlite3_memory_alarm(arg0: fn(RawPtr<u8>, i64, i32), arg1: RawPtr<u8>, arg2: i64) -> i32
pub extern "C" fn sqlite3_value_blob(arg0: RawPtr<Sqlite3Value>) -> RawPtr<u8>
pub extern "C" fn sqlite3_value_double(arg0: RawPtr<Sqlite3Value>) -> f64
pub extern "C" fn sqlite3_value_int(arg0: RawPtr<Sqlite3Value>) -> i32
pub extern "C" fn sqlite3_value_int64(arg0: RawPtr<Sqlite3Value>) -> i64
pub extern "C" fn sqlite3_value_pointer(arg0: RawPtr<Sqlite3Value>, arg1: RawPtr<i8>) -> RawPtr<u8>
pub extern "C" fn sqlite3_value_text(arg0: RawPtr<Sqlite3Value>) -> RawPtr<u8>
pub extern "C" fn sqlite3_value_text16(arg0: RawPtr<Sqlite3Value>) -> RawPtr<u8>
pub extern "C" fn sqlite3_value_text16le(arg0: RawPtr<Sqlite3Value>) -> RawPtr<u8>
pub extern "C" fn sqlite3_value_text16be(arg0: RawPtr<Sqlite3Value>) -> RawPtr<u8>
pub extern "C" fn sqlite3_value_bytes(arg0: RawPtr<Sqlite3Value>) -> i32
pub extern "C" fn sqlite3_value_bytes16(arg0: RawPtr<Sqlite3Value>) -> i32
pub extern "C" fn sqlite3_value_type(arg0: RawPtr<Sqlite3Value>) -> i32
pub extern "C" fn sqlite3_value_numeric_type(arg0: RawPtr<Sqlite3Value>) -> i32
pub extern "C" fn sqlite3_value_nochange(arg0: RawPtr<Sqlite3Value>) -> i32
pub extern "C" fn sqlite3_value_frombind(arg0: RawPtr<Sqlite3Value>) -> i32
pub extern "C" fn sqlite3_value_encoding(arg0: RawPtr<Sqlite3Value>) -> i32
pub extern "C" fn sqlite3_value_subtype(arg0: RawPtr<Sqlite3Value>) -> u32
pub extern "C" fn sqlite3_value_dup(arg0: RawPtr<Sqlite3Value>) -> RawPtr<Sqlite3Value>
pub extern "C" fn sqlite3_value_free(arg0: RawPtr<Sqlite3Value>)
pub extern "C" fn sqlite3_aggregate_context(arg0: RawPtr<Sqlite3Context>, nbytes: i32) -> RawPtr<u8>
pub extern "C" fn sqlite3_user_data(arg0: RawPtr<Sqlite3Context>) -> RawPtr<u8>
pub extern "C" fn sqlite3_context_db_handle(arg0: RawPtr<Sqlite3Context>) -> RawPtr<Sqlite3>
pub extern "C" fn sqlite3_get_auxdata(arg0: RawPtr<Sqlite3Context>, n: i32) -> RawPtr<u8>
pub extern "C" fn sqlite3_set_auxdata(arg0: RawPtr<Sqlite3Context>, n: i32, arg2: RawPtr<u8>, arg3: fn(RawPtr<u8>))
pub extern "C" fn sqlite3_get_clientdata(arg0: RawPtr<Sqlite3>, arg1: RawPtr<i8>) -> RawPtr<u8>
pub extern "C" fn sqlite3_set_clientdata(arg0: RawPtr<Sqlite3>, arg1: RawPtr<i8>, arg2: RawPtr<u8>, arg3: fn(RawPtr<u8>)) -> i32
pub extern "C" fn sqlite3_result_blob(arg0: RawPtr<Sqlite3Context>, arg1: RawPtr<u8>, arg2: i32, arg3: fn(RawPtr<u8>))
pub extern "C" fn sqlite3_result_blob64(arg0: RawPtr<Sqlite3Context>, arg1: RawPtr<u8>, arg2: u64, arg3: fn(RawPtr<u8>))
pub extern "C" fn sqlite3_result_double(arg0: RawPtr<Sqlite3Context>, arg1: f64)
pub extern "C" fn sqlite3_result_error(arg0: RawPtr<Sqlite3Context>, arg1: RawPtr<i8>, arg2: i32)
pub extern "C" fn sqlite3_result_error16(arg0: RawPtr<Sqlite3Context>, arg1: RawPtr<u8>, arg2: i32)
pub extern "C" fn sqlite3_result_error_toobig(arg0: RawPtr<Sqlite3Context>)
pub extern "C" fn sqlite3_result_error_nomem(arg0: RawPtr<Sqlite3Context>)
pub extern "C" fn sqlite3_result_error_code(arg0: RawPtr<Sqlite3Context>, arg1: i32)
pub extern "C" fn sqlite3_result_int(arg0: RawPtr<Sqlite3Context>, arg1: i32)
pub extern "C" fn sqlite3_result_int64(arg0: RawPtr<Sqlite3Context>, arg1: i64)
pub extern "C" fn sqlite3_result_null(arg0: RawPtr<Sqlite3Context>)
pub extern "C" fn sqlite3_result_text(arg0: RawPtr<Sqlite3Context>, arg1: RawPtr<i8>, arg2: i32, arg3: fn(RawPtr<u8>))
pub extern "C" fn sqlite3_result_text64(arg0: RawPtr<Sqlite3Context>, z: RawPtr<i8>, n: u64, arg3: fn(RawPtr<u8>), encoding: u8)
pub extern "C" fn sqlite3_result_text16(arg0: RawPtr<Sqlite3Context>, arg1: RawPtr<u8>, arg2: i32, arg3: fn(RawPtr<u8>))
pub extern "C" fn sqlite3_result_text16le(arg0: RawPtr<Sqlite3Context>, arg1: RawPtr<u8>, arg2: i32, arg3: fn(RawPtr<u8>))
pub extern "C" fn sqlite3_result_text16be(arg0: RawPtr<Sqlite3Context>, arg1: RawPtr<u8>, arg2: i32, arg3: fn(RawPtr<u8>))
pub extern "C" fn sqlite3_result_value(arg0: RawPtr<Sqlite3Context>, arg1: RawPtr<Sqlite3Value>)
pub extern "C" fn sqlite3_result_pointer(arg0: RawPtr<Sqlite3Context>, arg1: RawPtr<u8>, arg2: RawPtr<i8>, arg3: fn(RawPtr<u8>))
pub extern "C" fn sqlite3_result_zeroblob(arg0: RawPtr<Sqlite3Context>, n: i32)
pub extern "C" fn sqlite3_result_zeroblob64(arg0: RawPtr<Sqlite3Context>, n: u64) -> i32
pub extern "C" fn sqlite3_result_subtype(arg0: RawPtr<Sqlite3Context>, arg1: u32)
pub extern "C" fn sqlite3_create_collation(arg0: RawPtr<Sqlite3>, zname: RawPtr<i8>, etextrep: i32, parg: RawPtr<u8>, xcompare: fn(RawPtr<u8>, i32, RawPtr<u8>, i32, RawPtr<u8>) -> i32) -> i32
pub extern "C" fn sqlite3_create_collation_v2(arg0: RawPtr<Sqlite3>, zname: RawPtr<i8>, etextrep: i32, parg: RawPtr<u8>, xcompare: fn(RawPtr<u8>, i32, RawPtr<u8>, i32, RawPtr<u8>) -> i32, xdestroy: fn(RawPtr<u8>)) -> i32
pub extern "C" fn sqlite3_create_collation16(arg0: RawPtr<Sqlite3>, zname: RawPtr<u8>, etextrep: i32, parg: RawPtr<u8>, xcompare: fn(RawPtr<u8>, i32, RawPtr<u8>, i32, RawPtr<u8>) -> i32) -> i32
pub extern "C" fn sqlite3_collation_needed(arg0: RawPtr<Sqlite3>, arg1: RawPtr<u8>, arg2: fn(RawPtr<u8>, RawPtr<Sqlite3>, i32, RawPtr<i8>)) -> i32
pub extern "C" fn sqlite3_collation_needed16(arg0: RawPtr<Sqlite3>, arg1: RawPtr<u8>, arg2: fn(RawPtr<u8>, RawPtr<Sqlite3>, i32, RawPtr<u8>)) -> i32
pub extern "C" fn sqlite3_sleep(arg0: i32) -> i32
pub extern "C" var sqlite3_temp_directory: RawPtr<i8>
pub extern "C" var sqlite3_data_directory: RawPtr<i8>
pub extern "C" fn sqlite3_win32_set_directory(type: u64, zvalue: RawPtr<u8>) -> i32
pub extern "C" fn sqlite3_win32_set_directory8(type: u64, zvalue: RawPtr<i8>) -> i32
pub extern "C" fn sqlite3_win32_set_directory16(type: u64, zvalue: RawPtr<u8>) -> i32
pub extern "C" fn sqlite3_get_autocommit(arg0: RawPtr<Sqlite3>) -> i32
pub extern "C" fn sqlite3_db_handle(arg0: RawPtr<Sqlite3Stmt>) -> RawPtr<Sqlite3>
pub extern "C" fn sqlite3_db_name(db: RawPtr<Sqlite3>, n: i32) -> RawPtr<i8>
pub extern "C" fn sqlite3_db_filename(db: RawPtr<Sqlite3>, zdbname: RawPtr<i8>) -> RawPtr<i8>
pub extern "C" fn sqlite3_db_readonly(db: RawPtr<Sqlite3>, zdbname: RawPtr<i8>) -> i32
pub extern "C" fn sqlite3_txn_state(arg0: RawPtr<Sqlite3>, zschema: RawPtr<i8>) -> i32
pub extern "C" fn sqlite3_next_stmt(pdb: RawPtr<Sqlite3>, pstmt: RawPtr<Sqlite3Stmt>) -> RawPtr<Sqlite3Stmt>
pub extern "C" fn sqlite3_commit_hook(arg0: RawPtr<Sqlite3>, arg1: fn(RawPtr<u8>) -> i32, arg2: RawPtr<u8>) -> RawPtr<u8>
pub extern "C" fn sqlite3_rollback_hook(arg0: RawPtr<Sqlite3>, arg1: fn(RawPtr<u8>), arg2: RawPtr<u8>) -> RawPtr<u8>
pub extern "C" fn sqlite3_autovacuum_pages(db: RawPtr<Sqlite3>, arg1: fn(RawPtr<u8>, RawPtr<i8>, u32, u32, u32) -> u32, arg2: RawPtr<u8>, arg3: fn(RawPtr<u8>)) -> i32
pub extern "C" fn sqlite3_update_hook(arg0: RawPtr<Sqlite3>, arg1: fn(RawPtr<u8>, i32, RawPtr<i8>, RawPtr<i8>, i64), arg2: RawPtr<u8>) -> RawPtr<u8>
pub extern "C" fn sqlite3_enable_shared_cache(arg0: i32) -> i32
pub extern "C" fn sqlite3_release_memory(arg0: i32) -> i32
pub extern "C" fn sqlite3_db_release_memory(arg0: RawPtr<Sqlite3>) -> i32
pub extern "C" fn sqlite3_soft_heap_limit64(n: i64) -> i64
pub extern "C" fn sqlite3_hard_heap_limit64(n: i64) -> i64
pub extern "C" fn sqlite3_soft_heap_limit(n: i32)
pub extern "C" fn sqlite3_table_column_metadata(db: RawPtr<Sqlite3>, zdbname: RawPtr<i8>, ztablename: RawPtr<i8>, zcolumnname: RawPtr<i8>, pzdatatype: RawPtr<RawPtr<i8> >, pzcollseq: RawPtr<RawPtr<i8> >, pnotnull: RawPtr<i32>, pprimarykey: RawPtr<i32>, pautoinc: RawPtr<i32>) -> i32
pub extern "C" fn sqlite3_load_extension(db: RawPtr<Sqlite3>, zfile: RawPtr<i8>, zproc: RawPtr<i8>, pzerrmsg: RawPtr<RawPtr<i8> >) -> i32
pub extern "C" fn sqlite3_enable_load_extension(db: RawPtr<Sqlite3>, onoff: i32) -> i32
pub extern "C" fn sqlite3_auto_extension(xentrypoint: fn()) -> i32
pub extern "C" fn sqlite3_cancel_auto_extension(xentrypoint: fn()) -> i32
pub extern "C" fn sqlite3_reset_auto_extension()
pub extern "C" fn sqlite3_create_module(db: RawPtr<Sqlite3>, zname: RawPtr<i8>, p: RawPtr<Sqlite3Module>, pclientdata: RawPtr<u8>) -> i32
pub extern "C" fn sqlite3_create_module_v2(db: RawPtr<Sqlite3>, zname: RawPtr<i8>, p: RawPtr<Sqlite3Module>, pclientdata: RawPtr<u8>, xdestroy: fn(RawPtr<u8>)) -> i32
pub extern "C" fn sqlite3_drop_modules(db: RawPtr<Sqlite3>, azkeep: RawPtr<RawPtr<i8> >) -> i32
pub extern "C" fn sqlite3_declare_vtab(arg0: RawPtr<Sqlite3>, zsql: RawPtr<i8>) -> i32
pub extern "C" fn sqlite3_overload_function(arg0: RawPtr<Sqlite3>, zfuncname: RawPtr<i8>, narg: i32) -> i32
pub extern "C" fn sqlite3_blob_open(arg0: RawPtr<Sqlite3>, zdb: RawPtr<i8>, ztable: RawPtr<i8>, zcolumn: RawPtr<i8>, irow: i64, flags: i32, ppblob: RawPtr<RawPtr<Sqlite3Blob> >) -> i32
pub extern "C" fn sqlite3_blob_reopen(arg0: RawPtr<Sqlite3Blob>, arg1: i64) -> i32
pub extern "C" fn sqlite3_blob_close(arg0: RawPtr<Sqlite3Blob>) -> i32
pub extern "C" fn sqlite3_blob_bytes(arg0: RawPtr<Sqlite3Blob>) -> i32
pub extern "C" fn sqlite3_blob_read(arg0: RawPtr<Sqlite3Blob>, z: RawPtr<u8>, n: i32, ioffset: i32) -> i32
pub extern "C" fn sqlite3_blob_write(arg0: RawPtr<Sqlite3Blob>, z: RawPtr<u8>, n: i32, ioffset: i32) -> i32
pub extern "C" fn sqlite3_vfs_find(zvfsname: RawPtr<i8>) -> RawPtr<Sqlite3Vfs>
pub extern "C" fn sqlite3_vfs_register(arg0: RawPtr<Sqlite3Vfs>, makedflt: i32) -> i32
pub extern "C" fn sqlite3_vfs_unregister(arg0: RawPtr<Sqlite3Vfs>) -> i32
pub extern "C" fn sqlite3_mutex_alloc(arg0: i32) -> RawPtr<Sqlite3Mutex>
pub extern "C" fn sqlite3_mutex_free(arg0: RawPtr<Sqlite3Mutex>)
pub extern "C" fn sqlite3_mutex_enter(arg0: RawPtr<Sqlite3Mutex>)
pub extern "C" fn sqlite3_mutex_try(arg0: RawPtr<Sqlite3Mutex>) -> i32
pub extern "C" fn sqlite3_mutex_leave(arg0: RawPtr<Sqlite3Mutex>)
pub extern "C" fn sqlite3_mutex_held(arg0: RawPtr<Sqlite3Mutex>) -> i32
pub extern "C" fn sqlite3_mutex_notheld(arg0: RawPtr<Sqlite3Mutex>) -> i32
pub extern "C" fn sqlite3_db_mutex(arg0: RawPtr<Sqlite3>) -> RawPtr<Sqlite3Mutex>
pub extern "C" fn sqlite3_file_control(arg0: RawPtr<Sqlite3>, zdbname: RawPtr<i8>, op: i32, arg3: RawPtr<u8>) -> i32
pub extern "C" fn sqlite3_keyword_count() -> i32
pub extern "C" fn sqlite3_keyword_name(arg0: i32, arg1: RawPtr<RawPtr<i8> >, arg2: RawPtr<i32>) -> i32
pub extern "C" fn sqlite3_keyword_check(arg0: RawPtr<i8>, arg1: i32) -> i32
pub extern "C" fn sqlite3_str_new(arg0: RawPtr<Sqlite3>) -> RawPtr<Sqlite3Str>
pub extern "C" fn sqlite3_str_finish(arg0: RawPtr<Sqlite3Str>) -> RawPtr<i8>
pub extern "C" fn sqlite3_str_free(arg0: RawPtr<Sqlite3Str>)
pub extern "C" fn sqlite3_str_vappendf(arg0: RawPtr<Sqlite3Str>, zformat: RawPtr<i8>, arg2: RawPtr<i8>)
pub extern "C" fn sqlite3_str_append(arg0: RawPtr<Sqlite3Str>, zin: RawPtr<i8>, n: i32)
pub extern "C" fn sqlite3_str_appendall(arg0: RawPtr<Sqlite3Str>, zin: RawPtr<i8>)
pub extern "C" fn sqlite3_str_appendchar(arg0: RawPtr<Sqlite3Str>, n: i32, c: i8)
pub extern "C" fn sqlite3_str_reset(arg0: RawPtr<Sqlite3Str>)
pub extern "C" fn sqlite3_str_truncate(arg0: RawPtr<Sqlite3Str>, n: i32)
pub extern "C" fn sqlite3_str_errcode(arg0: RawPtr<Sqlite3Str>) -> i32
pub extern "C" fn sqlite3_str_length(arg0: RawPtr<Sqlite3Str>) -> i32
pub extern "C" fn sqlite3_str_value(arg0: RawPtr<Sqlite3Str>) -> RawPtr<i8>
pub extern "C" fn sqlite3_status(op: i32, pcurrent: RawPtr<i32>, phighwater: RawPtr<i32>, resetflag: i32) -> i32
pub extern "C" fn sqlite3_status64(op: i32, pcurrent: RawPtr<i64>, phighwater: RawPtr<i64>, resetflag: i32) -> i32
pub extern "C" fn sqlite3_db_status(arg0: RawPtr<Sqlite3>, op: i32, pcur: RawPtr<i32>, phiwtr: RawPtr<i32>, resetflg: i32) -> i32
pub extern "C" fn sqlite3_db_status64(arg0: RawPtr<Sqlite3>, arg1: i32, arg2: RawPtr<i64>, arg3: RawPtr<i64>, arg4: i32) -> i32
pub extern "C" fn sqlite3_stmt_status(arg0: RawPtr<Sqlite3Stmt>, op: i32, resetflg: i32) -> i32
pub extern "C" fn sqlite3_backup_init(pdest: RawPtr<Sqlite3>, zdestname: RawPtr<i8>, psource: RawPtr<Sqlite3>, zsourcename: RawPtr<i8>) -> RawPtr<Sqlite3Backup>
pub extern "C" fn sqlite3_backup_step(p: RawPtr<Sqlite3Backup>, npage: i32) -> i32
pub extern "C" fn sqlite3_backup_finish(p: RawPtr<Sqlite3Backup>) -> i32
pub extern "C" fn sqlite3_backup_remaining(p: RawPtr<Sqlite3Backup>) -> i32
pub extern "C" fn sqlite3_backup_pagecount(p: RawPtr<Sqlite3Backup>) -> i32
pub extern "C" fn sqlite3_unlock_notify(pblocked: RawPtr<Sqlite3>, xnotify: fn(RawPtr<RawPtr<u8> >, i32), pnotifyarg: RawPtr<u8>) -> i32
pub extern "C" fn sqlite3_stricmp(arg0: RawPtr<i8>, arg1: RawPtr<i8>) -> i32
pub extern "C" fn sqlite3_strnicmp(arg0: RawPtr<i8>, arg1: RawPtr<i8>, arg2: i32) -> i32
pub extern "C" fn sqlite3_strglob(zglob: RawPtr<i8>, zstr: RawPtr<i8>) -> i32
pub extern "C" fn sqlite3_strlike(zglob: RawPtr<i8>, zstr: RawPtr<i8>, cesc: u32) -> i32
pub extern "C" fn sqlite3_wal_hook(arg0: RawPtr<Sqlite3>, arg1: fn(RawPtr<u8>, RawPtr<Sqlite3>, RawPtr<i8>, i32) -> i32, arg2: RawPtr<u8>) -> RawPtr<u8>
pub extern "C" fn sqlite3_wal_autocheckpoint(db: RawPtr<Sqlite3>, n: i32) -> i32
pub extern "C" fn sqlite3_wal_checkpoint(db: RawPtr<Sqlite3>, zdb: RawPtr<i8>) -> i32
pub extern "C" fn sqlite3_wal_checkpoint_v2(db: RawPtr<Sqlite3>, zdb: RawPtr<i8>, emode: i32, pnlog: RawPtr<i32>, pnckpt: RawPtr<i32>) -> i32
pub extern "C" fn sqlite3_vtab_on_conflict(arg0: RawPtr<Sqlite3>) -> i32
pub extern "C" fn sqlite3_vtab_nochange(arg0: RawPtr<Sqlite3Context>) -> i32
pub extern "C" fn sqlite3_vtab_collation(arg0: RawPtr<Sqlite3IndexInfo>, arg1: i32) -> RawPtr<i8>
pub extern "C" fn sqlite3_vtab_distinct(arg0: RawPtr<Sqlite3IndexInfo>) -> i32
pub extern "C" fn sqlite3_vtab_in(arg0: RawPtr<Sqlite3IndexInfo>, icons: i32, bhandle: i32) -> i32
pub extern "C" fn sqlite3_vtab_in_first(pval: RawPtr<Sqlite3Value>, ppout: RawPtr<RawPtr<Sqlite3Value> >) -> i32
pub extern "C" fn sqlite3_vtab_in_next(pval: RawPtr<Sqlite3Value>, ppout: RawPtr<RawPtr<Sqlite3Value> >) -> i32
pub extern "C" fn sqlite3_vtab_rhs_value(arg0: RawPtr<Sqlite3IndexInfo>, arg1: i32, ppval: RawPtr<RawPtr<Sqlite3Value> >) -> i32
pub extern "C" fn sqlite3_stmt_scanstatus(pstmt: RawPtr<Sqlite3Stmt>, idx: i32, iscanstatusop: i32, pout: RawPtr<u8>) -> i32
pub extern "C" fn sqlite3_stmt_scanstatus_v2(pstmt: RawPtr<Sqlite3Stmt>, idx: i32, iscanstatusop: i32, flags: i32, pout: RawPtr<u8>) -> i32
pub extern "C" fn sqlite3_stmt_scanstatus_reset(arg0: RawPtr<Sqlite3Stmt>)
pub extern "C" fn sqlite3_db_cacheflush(arg0: RawPtr<Sqlite3>) -> i32
pub extern "C" fn sqlite3_system_errno(arg0: RawPtr<Sqlite3>) -> i32
pub extern "C" fn sqlite3_snapshot_get(db: RawPtr<Sqlite3>, zschema: RawPtr<i8>, ppsnapshot: RawPtr<RawPtr<Sqlite3Snapshot> >) -> i32
pub extern "C" fn sqlite3_snapshot_open(db: RawPtr<Sqlite3>, zschema: RawPtr<i8>, psnapshot: RawPtr<Sqlite3Snapshot>) -> i32
pub extern "C" fn sqlite3_snapshot_free(arg0: RawPtr<Sqlite3Snapshot>)
pub extern "C" fn sqlite3_snapshot_cmp(p1: RawPtr<Sqlite3Snapshot>, p2: RawPtr<Sqlite3Snapshot>) -> i32
pub extern "C" fn sqlite3_snapshot_recover(db: RawPtr<Sqlite3>, zdb: RawPtr<i8>) -> i32
pub extern "C" fn sqlite3_serialize(db: RawPtr<Sqlite3>, zschema: RawPtr<i8>, pisize: RawPtr<i64>, mflags: u32) -> RawPtr<u8>
pub extern "C" fn sqlite3_deserialize(db: RawPtr<Sqlite3>, zschema: RawPtr<i8>, pdata: RawPtr<u8>, szdb: i64, szbuf: i64, mflags: u32) -> i32
pub extern "C" fn sqlite3_carray_bind_v2(pstmt: RawPtr<Sqlite3Stmt>, i: i32, adata: RawPtr<u8>, ndata: i32, mflags: i32, xdel: fn(RawPtr<u8>), pdel: RawPtr<u8>) -> i32
pub extern "C" fn sqlite3_carray_bind(pstmt: RawPtr<Sqlite3Stmt>, i: i32, adata: RawPtr<u8>, ndata: i32, mflags: i32, xdel: fn(RawPtr<u8>)) -> i32
pub extern "C" fn sqlite3_rtree_geometry_callback(db: RawPtr<Sqlite3>, zgeom: RawPtr<i8>, xgeom: fn(RawPtr<Sqlite3RtreeGeometry>, i32, RawPtr<f64>, RawPtr<i32>) -> i32, pcontext: RawPtr<u8>) -> i32
pub extern "C" fn sqlite3_rtree_query_callback(db: RawPtr<Sqlite3>, zqueryfunc: RawPtr<i8>, xqueryfunc: fn(RawPtr<Sqlite3RtreeQueryInfo>) -> i32, pcontext: RawPtr<u8>, xdestructor: fn(RawPtr<u8>)) -> i32

// skipped: declaration 'sqlite3_version': flexible arrays are unsupported

// skipped: variadic function 'sqlite3_config' is unsupported

// skipped: variadic function 'sqlite3_db_config' is unsupported

// skipped: variadic function 'sqlite3_mprintf' is unsupported

// skipped: variadic function 'sqlite3_snprintf' is unsupported

// skipped: variadic function 'sqlite3_test_control' is unsupported

// skipped: variadic function 'sqlite3_str_appendf' is unsupported

// skipped: variadic function 'sqlite3_log' is unsupported

// skipped: variadic function 'sqlite3_vtab_config' is unsupported

// skipped: record 'Fts5ExtensionApi': C callback has more than 6 parameters, which is unsupported

// skipped: record 'fts5_tokenizer_v2': C callback has more than 6 parameters, which is unsupported

// skipped: record 'Fts5Api' depends on unsupported record 'Fts5ExtensionApi'
